<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.5.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\odia-extra.m3u">
      <LogicalName>odia-extra.m3u</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
